STATUS_SUSCEPTIBLE = 'Susceptible'
STATUS_EXPOSED = 'Exposed'
STATUS_INFECTED = 'Infected'
STATUS_INFECTED_ASYMPTOMATIC = 'Asymptomatic'
STATUS_RECOVERED = 'Recovered'
TIME_TO_RECOVER = 10
TIME_TO_INFECTION = 3