STATUS_INFECTED_ASYMPTOMATIC = 'Asymptomatic'
TIME_TO_RECOVER = 14
TIME_TO_INFECTION = 7
#TODO: kill everything above this line
STATUS_SUSCEPTIBLE = 'Susceptible'
STATUS_EXPOSED = 'Exposed'
STATUS_INFECTED = 'Infected'
STATUS_RECOVERED = 'Recovered'
DEFAULT_BETA = 1.75
DEFAULT_ALPHA = 0.2
DEFAULT_GAMMA = 0.5
MAP_LOCATION_JUNCTION_BLVD = 451
MAP_LOCATION_BRIGHTON_BEACH = 55
MAP_LOCATION_WUHAN_TIANHE = 3376